CREATE DEFINER=`root`@`localhost` PROCEDURE `fiatividade`.`FI_SP_IncClienteV2`(
    IN p_NOME VARCHAR(50),
    IN p_SOBRENOME VARCHAR(255),
    IN p_NACIONALIDADE VARCHAR(50),
    IN p_CEP VARCHAR(9),
    IN p_ESTADO VARCHAR(2),
    IN p_CIDADE VARCHAR(50),
    IN p_LOGRADOURO VARCHAR(500),
    IN p_EMAIL VARCHAR(2079),
    IN p_TELEFONE VARCHAR(15),
    IN p_CPF CHAR(14)
)
BEGIN
    INSERT INTO CLIENTES (NOME, SOBRENOME, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, CPF) 
    VALUES (p_NOME, p_SOBRENOME, p_NACIONALIDADE, p_CEP, p_ESTADO, p_CIDADE, p_LOGRADOURO, p_EMAIL, p_TELEFONE, p_CPF);

    SELECT LAST_INSERT_ID();
END