CREATE DEFINER=`root`@`localhost` PROCEDURE `fiatividade`.`FI_SP_ConsCliente`(
    IN p_ID BIGINT
)
BEGIN
    IF p_ID IS NULL OR p_ID = 0 THEN
        SELECT NOME, SOBRENOME, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, ID FROM CLIENTES;
    ELSE
        SELECT NOME, SOBRENOME, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, ID FROM CLIENTES WHERE ID = p_ID;
    END IF;
END;