CREATE OR REPLACE FUNCTION fi_sp_conscliente(_ID BIGINT)
RETURNS TABLE(
    NOME VARCHAR,
    SOBRENOME VARCHAR,
    NACIONALIDADE VARCHAR,
    CEP VARCHAR,
    ESTADO VARCHAR,
    CIDADE VARCHAR,
    LOGRADOURO VARCHAR,
    EMAIL VARCHAR,
    TELEFONE VARCHAR,
    CPF CHAR(14), -- Adicionando o campo CPF no retorno
    ID BIGINT
) AS $$
BEGIN
    IF _ID IS NULL OR _ID = 0 THEN
        RETURN QUERY SELECT NOME, SOBRENOME, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, CPF, ID FROM clientes;
    ELSE
        RETURN QUERY SELECT NOME, SOBRENOME, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, CPF, ID FROM clientes WHERE ID = _ID;
    END IF;
END;
$$ LANGUAGE plpgsql;
